version: "3"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      JDBC_URL: "jdbc:postgresql://db:5432/postgres"
      JDBC_USER: "user"
      JDBC_PASSWORD: "pass"
      JDBC_DRIVER: "org.postgresql.Driver"
  db:
    image: "postgres"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "pass"