version: "3"
services:
  web:
    container_name: web-seek
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      JDBC_URL: "jdbc:postgresql://db:5432/postgres"
      JDBC_USER: "postgres"
      JDBC_PASSWORD: "pass"
      JDBC_DRIVER: "org.postgresql.Driver"
  db:
    container_name: postgres-seek
    image: "postgres"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "pass"
    volumes:
      - "${PWD}/build/resources/main/sql/init-seek.sql:/docker-entrypoint-initdb.d/init-seek.sql"
