# todo documentation
micronaut:
  application:
    name: seek
datasources:
  default:
    url: ${JDBC_URL}
    username: ${JDBC_USER}
    password: ${JDBC_PASSWORD}
    driverClassName: ${JDBC_DRIVER}
jpa:
  default:
    packages-to-scan:
      - 'seek.domain.entity'
    properties:
      hibernate:
        hbm2dd1:
          auto: update
        show_sql: true